function add_comsol_model(obj,bottom_points,top_points)
% Adds COMSOL model
% It will probably break if all points are aligned
top_points= [top_points(1,:)+[-obj.clip_l 0];...
    top_points;...
    top_points(end,:)+[obj.base_l/2 0]];

bottom_points= [bottom_points(1,:)+[-obj.clip_l 0];...
    bottom_points;...
    bottom_points(end,:)+[obj.base_l/2 0]];

obj.comsol_EZ_model=COMSOL_ES_Model(bottom_points,top_points,...
    obj.thickness,obj.insulator_thickness,obj.sheet_width,obj.voltage);
%Make sure everything runs smoothly
obj.comsol_EZ_model.calculate_es_force(bottom_points(2:end-1,:))
end
