function add_analytical_model(obj)
obj.numerical_model=Parallel_Plates_ES_Model(initial_points,...
    obj.voltage,obj.eMed,obj.eAir,obj.eIns,...
    obj.insulator_thickness,...
    obj.EMaxMed,obj.EMaxAir,obj.dropVolume,...
    obj.sheet_width);
obj.numerical_model.calculate_es_force()
end