close all;
quiver(obj.electrostatic_model.comsol_EZ_model.xs,...
 obj.electrostatic_model.comsol_EZ_model.ys,...
 obj.electrostatic_model.comsol_EZ_model.xs*0,...
 obj.electrostatic_model.comsol_EZ_model.hs,0,'k')
% plot(obj.electrostatic_model.comsol_EZ_model.xs,...
% obj.electrostatic_model.comsol_EZ_model.ys+...
% obj.electrostatic_model.comsol_EZ_model.hs,'rx')
hold on
plot(obj.electrostatic_model.comsol_EZ_model.xs,...
obj.electrostatic_model.comsol_EZ_model.ys+...
obj.electrostatic_model.comsol_EZ_model.hs*0,'b-s')
hold on
plot(obj.electrostatic_model.comsol_EZ_model.xs_top,...
obj.electrostatic_model.comsol_EZ_model.ys_top+...
obj.electrostatic_model.comsol_EZ_model.hs*0,'r-s')
%%

close all;
quiver(obj.xs,...
 obj.ys,...
 obj.xs*0,...
 obj.hs,0,'k')
% plot(obj.electrostatic_model.comsol_EZ_model.xs,...
% obj.electrostatic_model.comsol_EZ_model.ys+...
% obj.electrostatic_model.comsol_EZ_model.hs,'rx')
hold on
plot(obj.xs,...
obj.ys+...
obj.hs*0,'b-s')
hold on
plot(obj.xs_top,...
obj.ys_top,'r-s')

%%


close all;
quiver(obj.xs_top,...
 obj.ys_top,...
 obj.xs_top*0,...
 -obj.hs_top,0,'k')

% quiver(obj.xs_top,...
%  obj.ys_top-obj.hs_top,'kx')
% plot(obj.electrostatic_model.comsol_EZ_model.xs,...
% obj.electrostatic_model.comsol_EZ_model.ys+...
% obj.electrostatic_model.comsol_EZ_model.hs,'rx')
hold on
plot(obj.xs_top,...
obj.ys,'b-s')
hold on
plot(obj.xs_top,...
obj.ys_top,'r-s')