%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/bruno/Repositories/Personal/MATLAB_Dissertation/Mechanical_Simulation/07_EZ_Parameter_estimation/data/steel_sheet_2_sides_orientation_fix_left_pos_fix_L_045_N11.txt
%
% Auto-generated by MATLAB on 15-Jun-2020 09:10:29

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 26);

% Specify range and delimiter
N=11;
filename="steel_sheet_2_sides_orientation_fix_left_pos_fix_L_045_N11.txt";
opts.DataLines = [1+2*N+2, Inf];
opts.Delimiter = [" "];

% Specify column names and types
opts.VariableNames = ["VarName1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26"];
opts.SelectedVariableNames = "VarName1";
opts.VariableTypes = ["double", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26"], "EmptyFieldRule", "auto");
folder_path="/home/bruno/Repositories/Personal/MATLAB_Dissertation/Mechanical_Simulation/07_EZ_Parameter_estimation/data/";
% Import the data
tbl = readtable([folder_path+filename], opts);

%% Convert to output type
VarName1 = tbl.VarName1;

%% Clear temporary variables
clear opts tbl